---
- hosts: 172.31.19.1 
  become: yes
  tasks:
  - name: i want to execute linux command
    command:  hostname -f
    register: myvariable
    # register is key work not a variable

  - name: i want to display first task result 
    debug:
       msg: "{{myvariable}}"

  - name: install git
    apt:
      name: git
      state: present
    when: myvariable.stderr ==""


  - name: install tree
    apt: 
      name: tree
      state:  present
    when: myvariable.stderr !=""
    